import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {
  const { data, isLoading, error } = api.example.getAll.useQuery();

  const sortedPlayers = data
    ?.map((player) => {
      return {
        player: player.name,
        team: player.team,
        adp: player.adp,
        bye: player.bye,
        position: player.role,
      };
    })
    .sort((a, b) => {
      return a.adp - b.adp;
    });

  if (isLoading) return <div>...Loading</div>;
  if (error) return <div>No data found</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 text-white">
          {JSON.stringify(sortedPlayers)}
        </div>
      </main>
    </>
  );
}
